import prisma from '../src/db/prisma.js';

async function test() {
  console.log('Testing Interview Session Creation via Prisma...');
  const session = await prisma.interviewSession.create({
    data: {
      id: 'test-session-' + Date.now(),
      status: 'IN_PROGRESS',
      targetRole: 'Full Stack Engineer',
      questions: {
        create: [
          { id: 'test-q-1-' + Date.now(), questionNumber: 1, questionText: 'Explain React virtual DOM.', category: 'TECHNICAL' }
        ]
      }
    },
    include: { questions: true }
  });
  console.log('Created session:', session.id, 'with questions:', session.questions.length);

  console.log('Testing Telemetry Batch Insert via Prisma...');
  await prisma.interviewTelemetry.createMany({
    data: [
      { id: 'telem-1-' + Date.now(), sessionId: session.id, eyeContact: 92, attention: 90, confidence: 85, emotion: 'Confident' },
      { id: 'telem-2-' + Date.now(), sessionId: session.id, eyeContact: 95, attention: 92, confidence: 88, emotion: 'Confident' }
    ]
  });
  const telemCount = await prisma.interviewTelemetry.count({ where: { sessionId: session.id } });
  console.log('Telemetry records inserted:', telemCount);

  console.log('Testing Answer Insert via Prisma...');
  const answer = await prisma.interviewAnswer.create({
    data: {
      id: 'test-ans-1-' + Date.now(),
      questionId: session.questions[0].id,
      transcript: 'The virtual DOM is an in-memory representation of the real DOM elements generated by React components.',
      overallScore: 88,
      technicalScore: 90,
      communicationScore: 85,
      confidenceScore: 85,
      eyeContactScore: 93.5,
      attentionScore: 91,
      dominantEmotion: 'Confident'
    }
  });
  console.log('Created answer:', answer.id);

  console.log('Testing InterviewAnalysis in Transaction via Prisma...');
  await prisma.$transaction([
    prisma.interviewSession.update({
      where: { id: session.id },
      data: { status: 'COMPLETED', overallScore: 88.5, completedAt: new Date() }
    }),
    prisma.interviewAnalysis.create({
      data: {
        id: 'anal-' + session.id,
        sessionId: session.id,
        overallScore: 88.5,
        communicationScore: 85,
        confidenceScore: 85,
        eyeContactScore: 93.5,
        attentionScore: 91,
        expressionScore: 88,
        technicalScore: 90,
        speechScore: 85,
        dominantEmotion: 'Confident',
        strengths: ['Great eye contact', 'Clear architecture explanation'],
        weaknesses: ['Could mention reconciliation algorithm'],
        recommendations: ['Practice explaining Fiber architecture']
      }
    })
  ]);

  const analysis = await prisma.interviewAnalysis.findUnique({ where: { sessionId: session.id } });
  console.log('Analysis verified successfully! Overall score:', analysis.overallScore, 'Emotion:', analysis.dominantEmotion);

  // Clean up test session
  await prisma.interviewSession.delete({ where: { id: session.id } });
  console.log('✅ Test session cleaned up successfully.');
}

test()
  .then(() => process.exit(0))
  .catch(err => {
    console.error('Test error:', err);
    process.exit(1);
  });
